#apiVersion: v1
#kind: Namespace
#metadata:
#  name: system
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-gateway
  namespace: system
  labels:
    control-plane: http-gateway
spec:
  selector:
    matchLabels:
      control-plane: http-gateway
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: http-gateway
    spec:
      containers:
      - name: http-gateway
        image: github.com/projectriff/http-gateway/cmd
