#apiVersion: v1
#kind: Namespace
#metadata:
#  name: system
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-gateway
  labels:
    control-plane: http-gateway
spec:
  selector:
    matchLabels:
      control-plane: http-gateway
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: http-gateway
    spec:
      containers:
      - name: http-gateway
        image: github.com/projectriff/http-gateway/cmd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: streaming.projectriff.io
    control-plane: http-gateway
  name: http-gateway
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    component: streaming.projectriff.io
    control-plane: http-gateway
  sessionAffinity: None
  type: ClusterIP
